-- City config v2: 14 new admin-configurable fields on ServiceableCity

ALTER TABLE "ServiceableCity"
  ADD COLUMN IF NOT EXISTS "autoCancelMinutes"       INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS "riderOfferWindowSec"     INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS "maxActiveOrdersPerRider" INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS "shopReminderMinutes"     INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS "staleRiderMinutes"       INTEGER NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS "nearbyShopsRadiusMeters" INTEGER NOT NULL DEFAULT 3000,
  ADD COLUMN IF NOT EXISTS "platformFeePaise"        INTEGER NOT NULL DEFAULT 1000,
  ADD COLUMN IF NOT EXISTS "defaultCommissionRate"   DOUBLE PRECISION NOT NULL DEFAULT 0.02,
  ADD COLUMN IF NOT EXISTS "defaultCreditLimitPaise" INTEGER NOT NULL DEFAULT 50000,
  ADD COLUMN IF NOT EXISTS "commissionHolidayDays"   INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS "onboardingFeePaise"      INTEGER NOT NULL DEFAULT 49900,
  ADD COLUMN IF NOT EXISTS "referralCustomerCoins"   INTEGER NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS "referralShopCoins"       INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS "codWindowHours"          INTEGER NOT NULL DEFAULT 24;
