ALTER TABLE "ServiceableCity" ADD COLUMN IF NOT EXISTS "codMinOrderPaise" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ServiceableCity" ADD COLUMN IF NOT EXISTS "codMaxPerDay" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "ServiceableCity" ADD COLUMN IF NOT EXISTS "codCancelBlockAfter" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "ServiceableCity" ADD COLUMN IF NOT EXISTS "codCancelWindowDays" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "codEnabled" BOOLEAN NOT NULL DEFAULT true;
