ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pendingCancelFeeShopId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cancelFeeLinePaise" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cancelFeeShopId" TEXT;
