ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "cancelFeeRatePct" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cancelRequestedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cancelRequestReason" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cancelFeePaise" INTEGER;
